# Generated by Django 3.2.13 on 2022-10-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
