# Generated by Django 3.2.13 on 2022-07-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220723_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_ingredient', to='recipes.IngredientRecipe', verbose_name='Продукты'),
        ),
    ]
